GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/14

###

POST http://localhost:3000/movies
Content-Type: application/json
{
  "title": "Green Eggs and Ham",
  "year": "Dr. Seuss",
  "plot": "Green Eggs, Ham"
}

###

PATCH http://localhost:3000/recipes/1
Content-Type: application/json

{
  "plot": "Han shot first"
}
###

DELETE http://localhost:3000/movies/2

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test User1",
  "email": "test1@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "test1@test.com",
    "password": "password"
  }

  ### Photos create
POST http://localhost:3000/photos
Authorization: Bearer 
Content-Type: application/json

  {
    "name": "Test name",
    "width": 640,
    "height": 480
  }